module.exports = Object.freeze({
    TASK_TYPE:'TASK_TYPE',       
    ALGORITHM_TYPE:'ALGORITHM_TYPE',
    ARRAY_CUSTOMERS:'ARRAY_CUSTOMERS',
    MATRIX_COST:'MATRIX_COST',
    N_TRUCKS:'N_TRUCKS',
    TRUCK_CAPACITY:'TRUCK_CAPACITY',
    TRUCK_TIME:'TRUCK_TIME',
    PENAL_CAP:'PENAL_CAP',
    PENAL_TIME:'PENAL_TIME',
    PROB_CROSS:'PROB_CROSS',
    PROB_MUT:'PROB_MUT',
    PROB_LS:'PROB_LS',
    CHROM_LENGTH:'CHROM_LENGTH',    
    TARGET_FITNESS:'TARGET_FITNESS',
    MAX_STEPS:'MAX_STEPS',
    POP_SIZE:'POP_SIZE',    
    
    PROBLEM:'PROBLEM',
    POPULATION:'POPULATION',
    
    REPLACEMENTS:'REPLACEMENTS',
    INDIVIDUAL:'INDIVIDUAL',
    TIME:'TIME',
    TOTAL_STEPS:'TOTAL_STEPS'   
});